### ISSUE TITLE
[request] start the server (after installed update)

### ISSUE THREAD

**Issue by MikkelDK** [Najsr/TeaSpeak-Updater#1]
Hi.

Is it possible, you can set. so the "script" will automatic start the server (if there is new update) > it stop the server i know. but more. so it can start after installation of the new update.

Thanks! ;D

**Comment by Najsr** [comment]
Should be implemented with commit https://github.com/Najsr/TeaSpeak-Updater/commit/cba0c034e297e7d4072677e0ff554090963adf98 
Feel free to test it :)

**Comment by MikkelDK** [comment]
I will test it now. ;)

**Comment by MikkelDK** [comment]
@Najsr - It wont start ;/

**Comment by Najsr** [comment]
Give me the arguments you are using for the script

**Comment by MikkelDK** [comment]
Hi.

I did try with ./teastart_update.sh --s and --start ;)
it just saying "UPTODATE"

**Comment by MikkelDK** [comment]
Cool! thanks mate! ;) /closed.
